/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EarRouteImport } from './routes/ear'
import { Route as IndexRouteImport } from './routes/index'

const EarRoute = EarRouteImport.update({
  id: '/ear',
  path: '/ear',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ear': typeof EarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ear': typeof EarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ear': typeof EarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ear'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ear'
  id: '__root__' | '/' | '/ear'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EarRoute: typeof EarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ear': {
      id: '/ear'
      path: '/ear'
      fullPath: '/ear'
      preLoaderRoute: typeof EarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EarRoute: EarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
