/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EarRouteImport } from './routes/ear'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EarIndexRouteImport } from './routes/ear.index'
import { Route as EarSegmentRouteImport } from './routes/ear.$segment'

const EarRoute = EarRouteImport.update({
  id: '/ear',
  path: '/ear',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EarIndexRoute = EarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EarRoute,
} as any)
const EarSegmentRoute = EarSegmentRouteImport.update({
  id: '/$segment',
  path: '/$segment',
  getParentRoute: () => EarRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ear': typeof EarRouteWithChildren
  '/ear/$segment': typeof EarSegmentRoute
  '/ear/': typeof EarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ear/$segment': typeof EarSegmentRoute
  '/ear': typeof EarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ear': typeof EarRouteWithChildren
  '/ear/$segment': typeof EarSegmentRoute
  '/ear/': typeof EarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ear' | '/ear/$segment' | '/ear/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ear/$segment' | '/ear'
  id: '__root__' | '/' | '/ear' | '/ear/$segment' | '/ear/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EarRoute: typeof EarRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ear': {
      id: '/ear'
      path: '/ear'
      fullPath: '/ear'
      preLoaderRoute: typeof EarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ear/': {
      id: '/ear/'
      path: '/'
      fullPath: '/ear/'
      preLoaderRoute: typeof EarIndexRouteImport
      parentRoute: typeof EarRoute
    }
    '/ear/$segment': {
      id: '/ear/$segment'
      path: '/$segment'
      fullPath: '/ear/$segment'
      preLoaderRoute: typeof EarSegmentRouteImport
      parentRoute: typeof EarRoute
    }
  }
}

interface EarRouteChildren {
  EarSegmentRoute: typeof EarSegmentRoute
  EarIndexRoute: typeof EarIndexRoute
}

const EarRouteChildren: EarRouteChildren = {
  EarSegmentRoute: EarSegmentRoute,
  EarIndexRoute: EarIndexRoute,
}

const EarRouteWithChildren = EarRoute._addFileChildren(EarRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EarRoute: EarRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
